#!/usr/bin/env bash  
#
# Startup script for solr using jetty under *nix systems (it works under NT/cygwin too).

### BEGIN INIT INFO
# Provides:          solr
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the jetty daemon at boot
# Description:       The service script for a solr-jetty instance
### END INIT INFO

# Configuration files
#
# /etc/default/solr-jetty
#   If it exists, this is read at the start of script. It may perform any 
#   sequence of shell commands, like setting relevant environment variables.
#
# $HOME/.solr-jettyrc
#   If it exists, this is read at the start of script. It may perform any 
#   sequence of shell commands, like setting relevant environment variables.
#
# /etc/solr-jetty.conf
#   If found, and no configurations were given on the command line,
#   the file will be used as this script's configuration. 
#   Each line in the file may contain:
#     - A comment denoted by the pound (#) sign as first non-blank character.
#     - The path to a regular file, which will be passed to jetty as a 
#       config.xml file.
#     - The path to a directory. Each *.xml file in the directory will be
#       passed to jetty as a config.xml file.
#
#   The files will be checked for existence before being passed to jetty.
#
# $JETTY_HOME/etc/jetty.xml
#   If found, used as this script's configuration file, but only if
#   /etc/solr-jetty.conf was not present. See above.
#   
# Configuration variables
#
# JAVA
#   Command to invoke Java. If not set, java (from the PATH) will be used.
#
# ZOOKEEPER_HOSTS
#   Command seperated list of Zookeeper hosts for solrCloud.  A non-standard
#   root can be specificed at the end of a host name
#   ex localhost:2182,example.com:2181,weirdroot.com:2181/other_root
#
# NUM_SHARDS
#   Specify the number of shards you'd like to user when working with SolrCloud
#
# JAVA_OPTIONS
#   Extra options to pass to the JVM
#
# JETTY_HOME
#   Where jetty is installed. If not set, the script will try go
#   guess it by first looking at the invocation path for the script,
#   and then by looking in standard locations as $HOME/opt/solr
#   and /opt/solr The java system property "jetty.home" will be
#   set to this value for use by configure.xml files, f.e.:
#
#    <Arg><Property name="solr.home" default="."/>/opt/solr/example`</Arg>
#
# SOLR_HOME
#   Where the solr.xml file can be found.  The java system property
#   "solr.home" will be set to this value
#
# SOLR_PORT
#   Override the default port for solr servers. If not set then the
#   default value in the xml configuration file will be used. The java
#   system property "jetty.port" will be set to this value for use in
#   configure.xml files. For example, the following idiom is widely
#   used in the demo config files to respect this property in Listener
#   configuration elements:
#
#    <Set name="Port"><Property name="jetty.port" default="8080"/></Set>
#
#   Note: that the config file could ignore this property simply by saying:
#
#    <Set name="Port">8080</Set>
#
# SOLR_RUN
#   Where the solr.pid file should be stored. It defaults to the
#   first available of /var/run, /usr/var/run, and /tmp if not set.
#  
# SOLR_PID
#   The solr PID file, defaults to $SOLR_RUN/solr.pid
#   
# SOLR_ARGS
#   The default arguments to pass to solr.
#
# SOLR_USER
#   if set, then used as a username to run the server as
#

usage()
{
    echo "Usage: ${0##*/} [-d] {start|stop|run|restart|check|supervise} [ CONFIGS ... ] "
    exit 1
}

[ $# -gt 0 ] || usage


##################################################
# Some utility functions
##################################################
findDirectory()
{
  local L OP=$1
  shift
  for L in "$@"; do
    [ "$OP" "$L" ] || continue 
    printf %s "$L"
    break
  done 
}

running()
{
  local PID=$(cat "$1" 2>/dev/null) || return 1
  kill -0 "$PID" 2>/dev/null
}

readConfig()
{
  (( DEBUG )) && echo "Reading $1.."
  source "$1"
}



##################################################
# Get the action & configs
##################################################
CONFIGS=()
NO_START=0
DEBUG=0

while [[ $1 = -* ]]; do
  case $1 in
    -d) DEBUG=1 ;;
  esac
  shift
done
ACTION=$1
shift

##################################################
# Read any configuration files
##################################################
for CONFIG in /etc/default/solr-jetty{,7} $HOME/.solr-jettyrc; do
  if [ -f "$CONFIG" ] ; then 
    readConfig "$CONFIG"
  fi
done


##################################################
# Set tmp if not already set.
##################################################
TMPDIR=${TMPDIR:-/tmp}

##################################################
# Jetty's hallmark
##################################################
SOLR_INSTALL_TRACE_FILE="etc/jetty.xml"


##################################################
# Try to determine JETTY_HOME if not set
##################################################
if [ -z "$JETTY_HOME" ] 
then
  SOLR_SH=$0
  case "$SOLR_SH" in
    /*)   ;;
    ./*)  ;;
    *)    SOLR_SH=./$SOLR_SH ;;
  esac
  JETTY_HOME=${SOLR_SH%/*/*}

  if [ ! -f "${SOLR_SH%/*/*}/$SOLR_INSTALL_TRACE_FILE" ]
  then 
    JETTY_HOME=
  fi
fi


##################################################
# if no JETTY_HOME, search likely locations.
##################################################
if [ -z "$JETTY_HOME" ] ; then
  STANDARD_LOCATIONS=(
        "/usr/share"
        "/usr/share/java"
        "${HOME}"
        "${HOME}/src"
        "${HOME}/opt"
        "/opt"
        "/java"
        "/usr/local"
        "/usr/local/share"
        "/usr/local/share/java"
        "/home"
        )
  SOLR_DIR_NAMES=(
        "solr"
        "solr4"
        "solr-4.3.*"
        )
        
  for L in "${STANDARD_LOCATIONS[@]}"
  do
    for N in "${SOLR_DIR_NAMES[@]}"
    do
      POSSIBLE_JETTY_HOME=("$L/"$N)
      if [ ! -d "$POSSIBLE_JETTY_HOME" ]
      then
        # Not a directory. skip.
        unset POSSIBLE_JETTY_HOME
      elif [ ! -f "$POSSIBLE_JETTY_HOME/$SOLR_INSTALL_TRACE_FILE" ]
      then
        # Trace file not found. skip.
        unset POSSIBLE_JETTY_HOME
      else
        # Good hit, Use it
        JETTY_HOME=$POSSIBLE_JETTY_HOME
        # Break out of SOLR_DIR_NAMES loop
        break
      fi
    done
    if [ -n "$POSSIBLE_JETTY_HOME" ]
    then
      # We have found our JETTY_HOME
      # Break out of STANDARD_LOCATIONS loop
      break
    fi
  done
fi


##################################################
# No JETTY_HOME yet? We're out of luck!
##################################################
if [ -z "$JETTY_HOME" ]; then
  echo "** ERROR: JETTY_HOME not set, you need to set it or install in a standard location" 
  exit 1
fi

cd "$JETTY_HOME"
JETTY_HOME=$PWD


#####################################################
# Check that jetty is where we think it is
#####################################################
if [ ! -r "$JETTY_HOME/$SOLR_INSTALL_TRACE_FILE" ] 
then
  echo "** ERROR: Oops! Jetty doesn't appear to be installed in $JETTY_HOME"
  echo "** ERROR:  $JETTY_HOME/$SOLR_INSTALL_TRACE_FILE is not readable!"
  exit 1
fi

##################################################
# Try to find this script's configuration file,
# but only if no configurations were given on the
# command line.
##################################################
if [ -z "$SOLR_CONF" ] 
then
  if [ -f /etc/solr-jetty.conf ]
  then
    SOLR_CONF=/etc/solr-jetty.conf
  elif [ -f "$JETTY_HOME/etc/solr-jetty.conf" ]
  then
    SOLR_CONF=$JETTY_HOME/etc/solr-jetty.conf
  fi
fi

##################################################
# Get the list of config.xml files from jetty.conf
##################################################
if [ -z "$CONFIGS" ] && [ -f "$SOLR_CONF" ] && [ -r "$SOLR_CONF" ] 
then
  while read -r CONF
  do
    if expr "$CONF" : '#' >/dev/null ; then
      continue
    fi

    if [ -d "$CONF" ] 
    then
      # assume it's a directory with configure.xml files
      # for example: /etc/jetty.d/
      # sort the files before adding them to the list of CONFIGS
      for XMLFILE in "$CONF/"*.xml
      do
        if [ -r "$XMLFILE" ] && [ -f "$XMLFILE" ] 
        then
          CONFIGS+=("$XMLFILE")
        else
          echo "** WARNING: Cannot read '$XMLFILE' specified in '$SOLR_CONF'" 
        fi
      done
    else
      # assume it's a command line parameter (let start.jar deal with its validity)
      CONFIGS+=("$CONF")
    fi
  done < "$SOLR_CONF"
fi

#####################################################
# Find a location for the pid file
#####################################################
if [ -z "$SOLR_RUN" ] 
then
  SOLR_RUN=$(findDirectory -w /var/run /usr/var/run /tmp)
fi

#####################################################
# Find a PID for the pid file
#####################################################
if [ -z "$SOLR_PID" ] 
then
  SOLR_PID="$SOLR_RUN/solr.pid"
fi

##################################################
# Setup JAVA if unset
##################################################
if [ -z "$JAVA" ]
then
  JAVA=$(which java)
fi

if [ -z "$JAVA" ]
then
  echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.5) in your PATH." 2>&2
  exit 1
fi

#####################################################
# See if Zookeeper is being used for SolrCloud
#####################################################

if [ "$ZOOKEEPER_HOSTS" ]
then
  JAVA_OPTIONS+=("-DzkHost=$ZOOKEEPER_HOSTS")
fi

#####################################################
# See if NUM_SHARDS is defined
#####################################################
if [ "$NUM_SHARDS" ]
then
  JAVA_OPTIONS+=("-DnumShards=$SOLR_PORT")
fi

#####################################################
# See if SOLR_PORT is defined
#####################################################
if [ "$SOLR_PORT" ] 
then
  JAVA_OPTIONS+=("-Djetty.port=$SOLR_PORT")
fi

#####################################################
# See if SOLR_LOGS is defined
#####################################################
if [ "$SOLR_LOGS" ]
then
  JAVA_OPTIONS+=("-Djetty.logs=$SOLR_LOGS")
fi

#####################################################
# Are we running on Windows? Could be, with Cygwin/NT.
#####################################################
case "`uname`" in
CYGWIN*) PATH_SEPARATOR=";";;
*) PATH_SEPARATOR=":";;
esac


#####################################################
# Add jetty properties to Java VM options.
#####################################################
JAVA_OPTIONS+=("-Dsolr.solr.home=$SOLR_HOME" "-Djetty.home=$JETTY_HOME" "-Djava.io.tmpdir=$TMPDIR")

[ -f "$JETTY_HOME/etc/start.config" ] && JAVA_OPTIONS=("-DSTART=$JETTY_HOME/etc/start.config" "${JAVA_OPTIONS[@]}")

#####################################################
# This is how the Jetty server will be started
#####################################################

SOLR_START=$JETTY_HOME/start.jar
[ ! -f "$SOLR_START" ] && SOLR_START=$JETTY_HOME/lib/start.jar

START_INI=$(dirname $SOLR_START)/start.ini
[ -r "$START_INI" ] || START_INI=""

RUN_ARGS=(${JAVA_OPTIONS[@]} -jar "$SOLR_START" $SOLR_ARGS "${CONFIGS[@]}")
RUN_CMD=("$JAVA" ${RUN_ARGS[@]})

#####################################################
# Comment these out after you're happy with what 
# the script is doing.
#####################################################
if (( DEBUG ))
then
  echo "JETTY_HOME     =  $JETTY_HOME"
  echo "SOLR_HOME     =  $SOLR_HOME"
  echo "SOLR_CONF     =  $SOLR_CONF"
  echo "SOLR_RUN      =  $SOLR_RUN"
  echo "SOLR_PID      =  $SOLR_PID"
  echo "SOLR_ARGS     =  $SOLR_ARGS"
  echo "CONFIGS        =  ${CONFIGS[*]}"
  echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
  echo "JAVA           =  $JAVA"
  echo "RUN_CMD        =  ${RUN_CMD}"
fi

##################################################
# Do the action
##################################################
case "$ACTION" in
  start)
    echo -n "Starting Solr on Jetty: "

    if (( NO_START )); then 
      echo "Not starting jetty - NO_START=1";
      exit
    fi

    if type start-stop-daemon > /dev/null 2>&1 
    then
      unset CH_USER
      if [ -n "$SOLR_USER" ]
      then
        CH_USER="-c$SOLR_USER"
      fi
      if start-stop-daemon -S -p"$SOLR_PID" $CH_USER -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
      then
        sleep 1
        if running "$SOLR_PID"
        then
          echo "OK"
        else
          echo "FAILED"
        fi
      fi

    else

      if [ -f "$SOLR_PID" ]
      then
        if running $SOLR_PID
        then
          echo "Already Running!"
          exit 1
        else
          # dead pid file - remove
          rm -f "$SOLR_PID"
        fi
      fi

      if [ "$SOLR_USER" ] 
      then
        touch "$SOLR_PID"
        chown "$SOLR_USER" "$SOLR_PID"
        # FIXME: Broken solution: wordsplitting, pathname expansion, arbitrary command execution, etc.
        su - "$SOLR_USER" -c "
          exec ${RUN_CMD[*]} --daemon &
          disown \$!
          echo \$! > '$SOLR_PID'"
      else
        "${RUN_CMD[@]}" &
        disown $!
        echo $! > "$SOLR_PID"
      fi

      echo "STARTED Solr on Jetty `date`" 
    fi

    ;;

  stop)
    echo -n "Stopping Solr on Jetty: "
    if type start-stop-daemon > /dev/null 2>&1; then
      start-stop-daemon -K -p"$SOLR_PID" -d"$JETTY_HOME" -a "$JAVA" -s HUP
      
      TIMEOUT=30
      while running "$SOLR_PID"; do
        if (( TIMEOUT-- == 0 )); then
          start-stop-daemon -K -p"$SOLR_PID" -d"$JETTY_HOME" -a "$JAVA" -s KILL
        fi

        sleep 1
      done

      rm -f "$SOLR_PID"
      echo OK
    else
      PID=$(cat "$SOLR_PID" 2>/dev/null)
      kill "$PID" 2>/dev/null
      
      TIMEOUT=30
      while running $SOLR_PID; do
        if (( TIMEOUT-- == 0 )); then
          kill -KILL "$PID" 2>/dev/null
        fi

        sleep 1
      done

      rm -f "$SOLR_PID"
      echo OK
    fi

    ;;

  restart)
    SOLR_SH=$0
    if [ ! -f $SOLR_SH ]; then
      if [ ! -f $JETTY_HOME/bin/jetty.sh ]; then
        echo "$JETTY_HOME/bin/jetty.sh does not exist."
        exit 1
      fi
      SOLR_SH=$JETTY_HOME/bin/jetty.sh
    fi

    "$SOLR_SH" stop "$@"
    "$SOLR_SH" start "$@"

    ;;

  supervise)
    #
    # Under control of daemontools supervise monitor which
    # handles restarts and shutdowns via the svc program.
    #
    exec "${RUN_CMD[@]}"

    ;;

  run|demo)
    echo "Running Solr on Jetty: "

    if [ -f "$SOLR_PID" ]
    then
      if running "$SOLR_PID"
      then
        echo "Already Running!"
        exit 1
      else
        # dead pid file - remove
        rm -f "$SOLR_PID"
      fi
    fi

    exec "${RUN_CMD[@]}"

    ;;

  check)
    echo "Checking arguments to Solr on Jetty: "
    echo "JETTY_HOME     =  $JETTY_HOME"
    echo "SOLR_CONF     =  $SOLR_CONF"
    echo "SOLR_RUN      =  $SOLR_RUN"
    echo "SOLR_PID      =  $SOLR_PID"
    echo "SOLR_PORT     =  $SOLR_PORT"
    echo "SOLR_LOGS     =  $SOLR_LOGS"
    echo "START_INI      =  $START_INI"
    echo "CONFIGS        =  ${CONFIGS[*]}"
    echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
    echo "JAVA           =  $JAVA"
    echo "CLASSPATH      =  $CLASSPATH"
    echo "RUN_CMD        =  ${RUN_CMD[*]}"
    echo
    
    if [ -f "$SOLR_PID" ]
    then
      echo "Solr on Jetty running pid=$(< "$SOLR_PID")"
      exit 0
    fi
    exit 1

    ;;

  *)
    usage

    ;;
esac

exit 0
